/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crud.views;

import java.awt.Color;

/**
 *
 * @author losmelli
 */
public class ChatBubble extends javax.swing.JPanel {

    /**
     * Creates new form ChatBubble
     */
    public ChatBubble() {
        initComponents();
        jTextArea1.setText(" jPanel3.add(Box.createVerticalStrut(15));\n" +
"        for (int i = 0; i < 10; i++) {\n" +
"            ChatBubble b = new ChatBubble();\n" +
"            jPanel3.add(b);\n" +
"            jPanel3.revalidate();\n" +
"            jPanel3.repaint();\n" +
"            jPanel3.add(Box.createVerticalStrut(15));\n" +
"\n" +" jPanel3.add(Box.createVerticalStrut(15));\n" +
"        for (int i = 0; i < 10; i++) {\n" +
"            ChatBubble b = new ChatBubble();\n" +
"            jPanel3.add(b);\n" +
"            jPanel3.revalidate();\n" +
"            jPanel3.repaint();\n" +
"            jPanel3.add(Box.createVerticalStrut(15));\n" +
"\n" +
"        }");
    }

    
    
    public void changecolour(Color color){
        setBackground(color);
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextArea1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(51, 255, 51));
        setPreferredSize(new java.awt.Dimension(200, 300));
        setLayout(new java.awt.BorderLayout());

        jTextArea1.setBackground(new java.awt.Color(255, 51, 153));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        add(jTextArea1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
